### ISSUE TITLE
VSQlik: Show Connection Settings is blank

### ISSUE THREAD

**Issue by davidwales** [q-masters/vsqlik#270]
**Describe the bug**
Running the command `VSQlik: Show Connection Settings` results in a blank page.

**To Reproduce**
1. Show commands (Shift-Ctrl-P)
2. Select `VSQlik: Show Connection Settings`
3. The settings page is blank

**Expected behavior**
The settings page would not be blank.

**Screenshots**
![Blank Settings Page](https://user-images.githubusercontent.com/55477181/85494309-bf6a2c00-b61b-11ea-95b6-1f953c4ae43a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro for Workstations, version 1909
 - VS Code version: 1.46.1

**Additional context**
The Console in 'Help -> Toggle Developer Tools' says:

```
webviewElement.ts:51 Webview: Cannot load resource outside of protocol root
(anonymous) @ webviewElement.ts:51
async function (async)
(anonymous) @ webviewElement.ts:43
apply @ callbacks-registry.ts:45
(anonymous) @ remote.js:286
(anonymous) @ remote.js:276
emit @ events.js:203
onMessage @ init.ts:59
```

**Comment by konne** [comment]
Hi, did you compiled the version from github? Or you downloaded the version from the Marketplace?
If you compile the project from scratch the settings are a subproject and need to be also compiled.
Usually this is done by npm run webview:build

**Comment by davidwales** [comment]
I downloaded it directly through the VS Code extension browser:

![image](https://user-images.githubusercontent.com/55477181/85508696-e9c9e280-b637-11ea-9f08-fbf652cf4cb4.png)

**Comment by konne** [comment]
Please update your vscode and try to update the extension.
There should be at least the version 0.1.0 available.

![image](https://user-images.githubusercontent.com/1100969/85508912-45bf4780-b5f5-11ea-8a44-90c889576645.png)

**Comment by davidwales** [comment]
When the extension is not installed, it has version v0.1.0. But when I install it, the version changes to 0.0.1.

Before install:
![image](https://user-images.githubusercontent.com/55477181/85509691-c6a03280-b639-11ea-9f83-11c7626f3e5b.png)

After install:
![image](https://user-images.githubusercontent.com/55477181/85509740-d9b30280-b639-11ea-8fd1-5bdae20f361f.png)

**Comment by countnazgul** [comment]
Just to confirm that this is the situation on my end as well -  downloading it from the marketplace the version is 0.0.1

**Comment by r-hannuschka** [comment]
@davidwales thx for the issue, this is very strange and working on this one. 

@konne 
is i see this corrrect this also fails on mac now (but i got both versions in my extension directory) the difference between 0.0.1 and 0.1.0 is following in package.json

0.0.1

```json
"engines": {
    "vscode": "^1.45.1"
},
```

0.1.0

```json
"engines": {
    "vscode": "1.45.1"
},
```

that could be the problem since vscode updates to 1.46, so we fixed this in #263 . To test i would say we could create the package 

```bash
npm run vsce:package
```

and simple put this one into the extension directory for vscode ? i also think you can install this file which will created with vsce have to check how.

**Comment by r-hannuschka** [comment]
Yeah as i see this right, i fixed this as i installed vscode 1.46.x on my computer i get warning.

commit https://github.com/q-masters/vsqlik/commit/1389f25baa46819b3d6ab9e11c354104fc5fa5f8#diff-59f51de4945d3a9a80a254062862997b 

So this should be in development branch, but we cant publish that one since the typings was a newer version and we get a conflict.

**Comment by r-hannuschka** [comment]
new version is up (0.3.0) should be the latest now. I just tested it and it was working for now. If you can confirm we can close this issue and sry for that :)

Best,
Ralf

**Comment by konne** [comment]
@countnazgul @davidwales  please can you test again

**Comment by yossirosset** [comment]
@r-hannuschka still happening in version 0.3.0

Error: Unable to read file '\.\styles.0220be4e5426a6fb155d.css' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'C:\styles.0220be4e5426a6fb155d.css')
    at e.doReadAsFileStream (fileService.ts:457)
resourceLoader.ts:59 Error: Unable to read file '\.\runtime-es2015.0dae8cbc97194c7caed4.js' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'C:\runtime-es2015.0dae8cbc97194c7caed4.js')
    at e.doReadAsFileStream (fileService.ts:457)
resourceLoader.ts:59 Error: Unable to read file '\.\polyfills-es2015.9ad3fb84653bac45550c.js' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'C:\polyfills-es2015.9ad3fb84653bac45550c.js')
    at e.doReadAsFileStream (fileService.ts:457)
resourceLoader.ts:59 Error: Unable to read file '\.\main-es2015.6b2d4133771fe80dbff8.js' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'C:\main-es2015.6b2d4133771fe80dbff8.js')
    at e.doReadAsFileStream (fileService.ts:457)

**Comment by r-hannuschka** [comment]
okay we check this, otherwise as work around not nice i know but for testing this will work until we fix this issue since i could not reproduce this one.

But what the webview currently does is only provide an interface to add / update / delete server settings and write this down into the settings.json file. 

So what you can do is enter the settings manually there so that the Command: VsQlik.Connect should work until we fixed that problem.

![image](https://user-images.githubusercontent.com/25415574/85553816-9ef29f80-b624-11ea-9d2c-d08f05045da9.png)

Click on the gears > Extension Settings > edit in settings.json and add this

```json
{
    ...,
    "VsQlik.Servers": [
        {
            "connection": {
                "allowUntrusted": false,
                "authorization": {
                    "data": {
                        "domain": "domain\\user",
                        "password": "password"
                    },
                    "strategy": 1
                },
                "host": "hostname",
                "path": null,
                "port": null,
                "secure": true
            },
            "fileRenderer": "0",
            "label": "windows-10-vm"
        },
        {
            ... second server
        }
    ],
}
```

Maybe we dont get this issue here because i also have the source code on my pc dont know, it seems the path to the webview (angular app) is wrong or missing maybe. So working on this now and hopefully we could solve this quickly

**Comment by countnazgul** [comment]
Its working for me - can connect to QSE and perform operations over apps. But ... not sure if because i've installed the extensions using the WSL but its working only for WSL. The normal VSCode  - not working. I'll test later to install it without WSL

**Comment by r-hannuschka** [comment]
Yeah i can reproduce this now, i open my windows  and installed vscode the first time. And if i install via plugins i get the same error, so at the end i can reproduce this now. But dont know why this is happening sos i search for that and will tell you if i find out something.

**Comment by yossirosset** [comment]
@r-hannuschka 
editing the JSON solved the issue, my json had slightly different structure, and I guess that was the problem.
My JSON loooked like this:
{
    "VsQlik.Servers": [
    
        {
            "label": "Localhost",
            "connection": {
                "host": "127.0.0.1",
                "path": null,
                "port": null,
                "secure": true,
                "allowUntrusted": false,
                "authorization": {
                    "strategy": 1,
                    "data": {
                        "domain": "",
                        "password": ""
                    }
                }
            },
            "renderer": 1
        }
    ]
}

**Comment by r-hannuschka** [comment]
No Json looks good, diffrent structure should not be the problem, the settings webview now working ? I mean on my Windows i just see nothing so i would say no, maybe the error is he dont find any settings since they dont exists and crashed then ?

Well have to check this one

**Comment by countnazgul** [comment]
@r-hannuschka the windows subsystem for linux. So technically im on windows but my vscode is connecting and running code under linux (locally). And the extensions can be different (using the wsl connection and the "native" windows one)

**Comment by yossirosset** [comment]
Setting page still blank, but the connection is working. fantastic work.

**Comment by r-hannuschka** [comment]
Yeah would be better the webview will be working ;) but nice to hear this quick fix does it, but i have to bring back the settings webview otherwise well ... not nice

**Comment by r-hannuschka** [comment]
I think i found it, the webview try to load javascript files (angular app) from hard disk, if i remove them yeah i see a webview, to fix this issue i think we have to render all angular content directly into the html file.

**Comment by konne** [comment]
@countnazgul @yossirosset @davidwales new release is done. 
Please test new Version 0.4.0

**Comment by yossirosset** [comment]
@konne @r-hannuschka , it works, thanks.

**Comment by countnazgul** [comment]
Yep. Works for me as well for QSE (both Windows and WSL)!!!

btw this might be for a new issue but seems that I cant connect to Qlik Core. might be only me though just checking if its ok with you

**Comment by r-hannuschka** [comment]
Yeah just open a new Issue for that, Qlik Core i think this is only Docker? Currently we have only 1 authorization method implemented (Form) which calls your Qlik Sense Server and sends a post request with the login credentials, i just have to implement other authorization methods maybe this would be the use case for that.

At the end we plan you can add your own authorization method, but this was not working for me currently. You are also welcome to create a pull request on this to help us :)

**Comment by davidwales** [comment]
I missed all the fun (different time zone), but I can confirm that v0.4.0 has appeared in my extensions. After updating, I can now see the connection settings!!!
